data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9YXpkZXZudWNvdXJzZTJwcm9qO0FjY291bnRLZXk9L1hiaFlLYVo0TUVBU0dEUGE1K09NMnZhL2l6SjFzODU2YVVlZzdCNXBoZlpObkFBc0FnVENlRVcrZ25TOHJoRDZTTmhvMVBQTURqZVJlSXFzYllqK2c9PQ==
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: az-dev-nu-course2-aks-cluster
  namespace: default
---
data:
  host.master: UDh3MWNaMkVkdHhJVDI0eFNkTUt2S2tSQXVCa2lMLzA4OGVQYWJwci9qS3hVckhWaUllVlN3PT0=
  host.function.default: cnF2QzNNYU9WMWlPMlFUazA3VmFCYnhVSnBGN0dLSVNLaDcwSUI5eTJkTmhiVElHcWtWMlJBPT0=
  host.systemKey.default: RVJXS2ZRbVhsNFZSWmlhY1czSE5ET0Z0Ty9OMTJlQnhvcUxYRnV5cUJKRlVWeVlwekc0dkJ3PT0=
  functions.createadvertisement.default: VVJRcG1uUXpiTFh2WnIyL25yUHRtcHJybjhtOHRFVWNCeEFiamtwYVRyQnFaUmZkZnBkYzdBPT0=
  functions.deleteadvertisement.default: M3JUZTRBaG1sV3RXRU1mb3FOZm5xMjhxQUxxOUprbVlGdGNBcWIyV2hLNU8vdXBiWXlxSzFBPT0=
  functions.getadvertisement.default: ZkV5VFFiNkVJRWJrUkVQcFJDYktCQTZqQVZHVHpLYklTMFZrdTRWOUJrQUpiOUdxYUhDUnR3PT0=
  functions.getadvertisements.default: dVo5cGJJZEE5YnhwNmxuc0lLV0JkdTNJRFB2cWttVDZqVi82UmRENFlNL1lzMUEzcDhmWE9RPT0=
  functions.getpost.default: OFI3R3ZFY0F1MkdzOE9OZ0ZybkduTzE5YWR2SDBodHovQUthN0s2R3Z1Rlg1MnZYdUJYYlZRPT0=
  functions.getposts.default: RnVSc3lsNUt1ZkFVdzIzd0xxeWtiTnU5aXNpUFpsTFlkRTBUYmdUOEZraGJlYUQvZU1mdmVRPT0=
  functions.updateadvertisement.default: Y0NwdEp6cHBWT1RzL3gxTm1nUkdHMW5YdUpmZU01Vms4WVBlTTY2Wk44alF2akYvVjFLOVZnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-az-dev-nu-course2-aks-cluster
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: az-dev-nu-course2-aks-cluster-function-keys-identity-svc-act
  namespace: default
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: default
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: az-dev-nu-course2-aks-cluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: az-dev-nu-course2-aks-cluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: az-dev-nu-course2-aks-cluster-http
  namespace: default
spec:
  selector:
    app: az-dev-nu-course2-aks-cluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-dev-nu-course2-aks-cluster-http
  namespace: default
  labels:
    app: az-dev-nu-course2-aks-cluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-dev-nu-course2-aks-cluster-http
  template:
    metadata:
      labels:
        app: az-dev-nu-course2-aks-cluster-http
    spec:
      containers:
      - name: az-dev-nu-course2-aks-cluster-http
        image: azdevnuregistry.azurecr.io/azdevnuproject:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-az-dev-nu-course2-aks-cluster
        envFrom:
        - secretRef:
            name: az-dev-nu-course2-aks-cluster
      serviceAccountName: az-dev-nu-course2-aks-cluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-dev-nu-course2-aks-cluster
  namespace: default
  labels:
    app: az-dev-nu-course2-aks-cluster
spec:
  selector:
    matchLabels:
      app: az-dev-nu-course2-aks-cluster
  template:
    metadata:
      labels:
        app: az-dev-nu-course2-aks-cluster
    spec:
      containers:
      - name: az-dev-nu-course2-aks-cluster
        image: azdevnuregistry.azurecr.io/azdevnuproject:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: az-dev-nu-course2-aks-cluster
      serviceAccountName: az-dev-nu-course2-aks-cluster-function-keys-identity-svc-act
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: az-dev-nu-course2-aks-cluster
  namespace: default
  labels:
    deploymentName: az-dev-nu-course2-aks-cluster
spec:
  scaleTargetRef:
    deploymentName: az-dev-nu-course2-aks-cluster
  triggers:
  - type: eventgridtrigger
    metadata:
      type: eventGridTrigger
      name: event
      direction: in
      eventHubName: az-dev-nu-course2-eh/az-dev-nu-course2-evthub
      connection: Endpoint=sb://az-dev-nu-course2-eh.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=m7zRoX1wUmJ9eXlOf/IK1GgX2On4dag0Qh5i+E7bgf0=
---

